import type { AssetRecipe, BuildingScene, DoorSpec, RectSpec } from './types';

const outerWalls = (entry = false): RectSpec[] => [
  { id: 'outer-n', x: 90, y: 50, width: 780, height: 18 },
  { id: 'outer-w', x: 90, y: 50, width: 18, height: 520 },
  { id: 'outer-e', x: 852, y: 50, width: 18, height: 520 },
  ...(entry
    ? [
        { id: 'outer-s-a', x: 90, y: 552, width: 86, height: 18 },
        { id: 'outer-s-b', x: 256, y: 552, width: 614, height: 18 },
      ]
    : [{ id: 'outer-s', x: 90, y: 552, width: 780, height: 18 }]),
];

const door = (
  id: string,
  name: string,
  x: number,
  y: number,
  angle: number,
  min: number,
  max: number,
): DoorSpec => ({
  id,
  name,
  hinge: { x, y },
  length: 76,
  width: 11,
  closedAngle: angle,
  minAngle: min,
  maxAngle: max,
  frontAsset: 'door.painted.front',
  backAsset: 'door.painted.back',
});

export const assetRecipes: AssetRecipe[] = [
  {
    id: 'floor.oak',
    name: '旧橡木地板',
    kind: 'tile',
    description: '可无缝平铺；图像只定义反照率，阴影由引擎计算。',
    prompt: 'Seamless worn oak plank floor texture, strict orthographic top-down, neutral diffuse light, no objects, no perspective, no shadows.',
    source: '/assets/floor-oak.png',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 2, y: 2 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.3, friction: 0.72 },
  },
  {
    id: 'floor.carpet',
    name: '磨损地毯',
    kind: 'tile',
    description: '卧室和楼梯平台使用的低反差地毯。',
    prompt: 'Seamless worn charcoal loop-pile carpet texture, strict top-down, flat diffuse light, subtle domestic wear, no objects.',
    state: 'recipe',
    side: 'top',
    physicalSize: { x: 2, y: 2 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.18, friction: 0.9 },
  },
  {
    id: 'wall.paper.face',
    name: '墙纸内墙面',
    kind: 'wall-face',
    description: '熟悉的住家墙面；声音遮挡与穿透参数独立保存。',
    prompt: 'Straight-on faded domestic wallpaper wall face, subtle age and lived-in detail, seamless, neutral diffuse light, no decor.',
    state: 'recipe',
    side: 'front',
    physicalSize: { x: 2, y: 2.6 },
    pivot: { x: 0.5, y: 1 },
    material: { penetration: 'soft', occlusion: 0.55, friction: 0.6 },
  },
  {
    id: 'wall.plaster.top',
    name: '墙体切面',
    kind: 'wall-face',
    description: '俯视时看到的墙厚切面，与墙纸分开生成。',
    prompt: 'Orthographic top cut surface of an aged plaster and timber stud interior wall strip, isolated texture, no perspective.',
    state: 'recipe',
    side: 'top',
    physicalSize: { x: 2, y: 0.18 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.55, friction: 0.6 },
  },
  {
    id: 'door.painted.front',
    name: '门 · 走廊面',
    kind: 'door-face',
    description: '门的走廊一面；门轴、厚度、锁和碰撞不烘进图里。',
    prompt: 'Single aged off-white painted townhouse interior door front face, orthographic, isolated, full rectangle, brass handle, no frame.',
    state: 'recipe',
    side: 'front',
    physicalSize: { x: 0.86, y: 2.04 },
    pivot: { x: 0, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.7, friction: 0.55 },
  },
  {
    id: 'door.painted.back',
    name: '门 · 房间面',
    kind: 'door-face',
    description: '同一扇门的背面，必须独立生成以支持推门观察。',
    prompt: 'Matching reverse face of one aged off-white painted townhouse interior door, orthographic, isolated, brass handle opposite side, no frame.',
    state: 'recipe',
    side: 'back',
    physicalSize: { x: 0.86, y: 2.04 },
    pivot: { x: 0, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.7, friction: 0.55 },
  },
  {
    id: 'prop.bed',
    name: '未整理床铺',
    kind: 'prop',
    description: '家具是透明背景图，遮挡体和可藏匿区域另存。',
    prompt: 'One lived-in unmade bed, strict 90-degree overhead, grounded realism, transparent background, no baked cast shadow.',
    state: 'recipe',
    side: 'top',
    physicalSize: { x: 2, y: 1.5 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.45, friction: 0.8 },
  },
  {
    id: 'character.operator',
    name: '战术操作员',
    kind: 'character',
    description: '玩家渲染图；移动胶囊、视野和队伍逻辑全部独立。',
    prompt: 'One fictional modern tactical response operator, strict 90-degree overhead, dark unbranded equipment, transparent background.',
    source: '/assets/operator-walk-4x4-rgba.png',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 0.62, y: 0.62 },
    pivot: { x: 0.5, y: 0.6 },
    atlas: { columns: 4, rows: 4, fps: 8, directions: ['north', 'east', 'south', 'west'] },
  },
  {
    id: 'character.resident',
    name: '住户基础体',
    kind: 'character',
    description: '演示住户。实际生产中由角色母版继续编辑成不同服装和状态。',
    prompt: 'One ordinary adult townhouse resident, strict 90-degree overhead, neutral clothes, transparent background, no weapon.',
    source: '/assets/character-explorer.png',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 0.58, y: 0.58 },
    pivot: { x: 0.5, y: 0.58 },
  },
];

export const buildingScene: BuildingScene = {
  version: 1,
  name: 'NO. 47 / ORIGINAL TOWNHOUSE',
  world: { width: 960, height: 620, pixelsPerMeter: 80 },
  styleLock: {
    id: 'grounded-night-townhouse-v1',
    projection: 'strict 90-degree orthographic top-down',
    lighting: 'neutral material light; all darkness, NV and cast shadows are runtime effects',
    palette: 'aged London townhouse, muted domestic colors, dark tactical equipment',
    negative: 'no franchise characters, no perspective, no complete room scene, no baked cast shadows, no text, no watermark',
  },
  assets: assetRecipes,
  floors: [
    {
      id: 'b1', index: 0, name: 'B1', subtitle: '地下室 · 设备 / 储藏', spawn: { x: 210, y: 485 },
      stairs: { id: 'stairs-b1', x: 112, y: 370, width: 108, height: 155, toUp: 'f1' },
      rooms: [
        { id: 'boiler', name: '锅炉间', purpose: 'utility', x: 108, y: 68, width: 270, height: 270, floorAsset: 'floor.oak', tint: 'rgba(40,64,55,.34)' },
        { id: 'store', name: '储藏间', purpose: 'storage', x: 396, y: 68, width: 456, height: 270, floorAsset: 'floor.oak', tint: 'rgba(48,51,46,.28)' },
        { id: 'cellar', name: '地下走廊', purpose: 'hall', x: 108, y: 356, width: 744, height: 196, floorAsset: 'floor.oak', tint: 'rgba(20,34,30,.32)' },
      ],
      walls: [...outerWalls(), { id: 'b1-v-a', x: 378, y: 50, width: 18, height: 126 }, { id: 'b1-v-b', x: 378, y: 252, width: 18, height: 104 }, { id: 'b1-h-a', x: 90, y: 338, width: 202, height: 18 }, { id: 'b1-h-b', x: 368, y: 338, width: 502, height: 18 }],
      doors: [door('b1-store-door', '储藏门', 387, 176, Math.PI / 2, 0, Math.PI / 2), door('b1-hall-door', '锅炉门', 292, 347, 0, -Math.PI / 2, 0)],
      occupants: [{ id: 'b1-unknown', name: '未知住户', position: { x: 700, y: 182 }, facing: 2.4, role: 'unknown', behavior: 'hiding', asset: 'character.resident' }],
      lights: [{ id: 'b1-bulb', position: { x: 285, y: 208 }, radius: 180, intensity: .62, enabled: true }],
    },
    {
      id: 'f1', index: 1, name: '1F', subtitle: '入口 · 厨房 / 起居', spawn: { x: 215, y: 500 },
      stairs: { id: 'stairs-f1', x: 112, y: 352, width: 108, height: 176, toUp: 'f2', toDown: 'b1' },
      rooms: [
        { id: 'foyer', name: '入口厅', purpose: 'entry', x: 108, y: 68, width: 200, height: 266, floorAsset: 'floor.oak', tint: 'rgba(48,62,55,.22)' },
        { id: 'living', name: '起居室', purpose: 'living', x: 326, y: 68, width: 280, height: 266, floorAsset: 'floor.oak', tint: 'rgba(89,64,48,.18)' },
        { id: 'kitchen', name: '厨房', purpose: 'kitchen', x: 624, y: 68, width: 228, height: 266, floorAsset: 'floor.oak', tint: 'rgba(63,72,67,.23)' },
        { id: 'hall', name: '楼梯厅', purpose: 'stairs', x: 108, y: 352, width: 244, height: 200, floorAsset: 'floor.oak', tint: 'rgba(30,46,41,.28)' },
        { id: 'dining', name: '餐区', purpose: 'dining', x: 370, y: 352, width: 482, height: 200, floorAsset: 'floor.oak', tint: 'rgba(94,75,51,.16)' },
      ],
      walls: [...outerWalls(true), { id: 'f1-v1-a', x: 308, y: 50, width: 18, height: 116 }, { id: 'f1-v1-b', x: 308, y: 242, width: 18, height: 110 }, { id: 'f1-v2-a', x: 606, y: 50, width: 18, height: 172 }, { id: 'f1-v2-b', x: 606, y: 298, width: 18, height: 54 }, { id: 'f1-h-a', x: 90, y: 334, width: 198, height: 18 }, { id: 'f1-h-b', x: 364, y: 334, width: 506, height: 18 }],
      doors: [door('f1-entry', '入口门', 176, 561, 0, -Math.PI / 2, 0), door('f1-living', '起居室门', 317, 166, Math.PI / 2, 0, Math.PI / 2), door('f1-kitchen', '厨房门', 615, 222, Math.PI / 2, 0, Math.PI / 2), door('f1-dining', '餐区门', 288, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f1-resident-a', name: '住户 A', position: { x: 470, y: 210 }, facing: 3.1, role: 'civilian', behavior: 'frozen', asset: 'character.resident' },
        { id: 'f1-unknown-b', name: '未知 B', position: { x: 744, y: 184 }, facing: 1.5, role: 'unknown', behavior: 'investigate', asset: 'character.resident' },
        { id: 'f1-hostile-c', name: '威胁 C', position: { x: 658, y: 450 }, facing: -1.2, role: 'hostile', behavior: 'patrol', asset: 'character.resident' },
      ],
      lights: [{ id: 'f1-lamp', position: { x: 470, y: 190 }, radius: 210, intensity: .74, enabled: true }, { id: 'f1-kitchen-light', position: { x: 744, y: 210 }, radius: 150, intensity: .58, enabled: false }],
    },
    {
      id: 'f2', index: 2, name: '2F', subtitle: '卧室 · 浴室 / 住户', spawn: { x: 166, y: 460 },
      stairs: { id: 'stairs-f2', x: 112, y: 352, width: 108, height: 176, toUp: 'f3', toDown: 'f1' },
      rooms: [
        { id: 'bed-a', name: '前卧室', purpose: 'bedroom', x: 108, y: 68, width: 294, height: 266, floorAsset: 'floor.carpet', tint: 'rgba(46,58,53,.24)' },
        { id: 'bath', name: '浴室', purpose: 'bathroom', x: 420, y: 68, width: 182, height: 266, floorAsset: 'floor.carpet', tint: 'rgba(52,72,72,.25)' },
        { id: 'bed-b', name: '后卧室', purpose: 'bedroom', x: 620, y: 68, width: 232, height: 266, floorAsset: 'floor.carpet', tint: 'rgba(72,52,54,.24)' },
        { id: 'landing', name: '楼梯平台', purpose: 'stairs', x: 108, y: 352, width: 248, height: 200, floorAsset: 'floor.carpet', tint: 'rgba(28,42,38,.3)' },
        { id: 'nursery', name: '儿童房', purpose: 'nursery', x: 374, y: 352, width: 478, height: 200, floorAsset: 'floor.carpet', tint: 'rgba(84,76,51,.17)' },
      ],
      walls: [...outerWalls(), { id: 'f2-v1-a', x: 402, y: 50, width: 18, height: 150 }, { id: 'f2-v1-b', x: 402, y: 276, width: 18, height: 76 }, { id: 'f2-v2-a', x: 602, y: 50, width: 18, height: 112 }, { id: 'f2-v2-b', x: 602, y: 238, width: 18, height: 114 }, { id: 'f2-h-a', x: 90, y: 334, width: 190, height: 18 }, { id: 'f2-h-b', x: 356, y: 334, width: 514, height: 18 }],
      doors: [door('f2-bed-a', '前卧室门', 411, 200, Math.PI / 2, 0, Math.PI / 2), door('f2-bed-b', '后卧室门', 611, 162, Math.PI / 2, 0, Math.PI / 2), door('f2-nursery', '儿童房门', 280, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f2-sleeper', name: '熟睡住户', position: { x: 260, y: 185 }, facing: 0, role: 'civilian', behavior: 'sleeping', asset: 'character.resident' },
        { id: 'f2-hidden', name: '床后未知目标', position: { x: 735, y: 244 }, facing: 2.8, role: 'unknown', behavior: 'hiding', asset: 'character.resident' },
        { id: 'f2-civilian', name: '住户 D', position: { x: 552, y: 452 }, facing: -2, role: 'civilian', behavior: 'frozen', asset: 'character.resident' },
        { id: 'f2-hostile', name: '威胁 E', position: { x: 750, y: 452 }, facing: -2.4, role: 'hostile', behavior: 'investigate', asset: 'character.resident' },
      ],
      lights: [{ id: 'f2-hall', position: { x: 320, y: 380 }, radius: 170, intensity: .5, enabled: true }, { id: 'f2-bed', position: { x: 710, y: 175 }, radius: 170, intensity: .42, enabled: false }],
    },
    {
      id: 'f3', index: 3, name: '3F', subtitle: '阁楼 · 工作室 / 储物', spawn: { x: 168, y: 462 },
      stairs: { id: 'stairs-f3', x: 112, y: 352, width: 108, height: 176, toDown: 'f2' },
      rooms: [
        { id: 'loft', name: '阁楼工作室', purpose: 'studio', x: 108, y: 68, width: 494, height: 266, floorAsset: 'floor.oak', tint: 'rgba(45,58,51,.28)' },
        { id: 'attic-store', name: '封闭储物间', purpose: 'storage', x: 620, y: 68, width: 232, height: 266, floorAsset: 'floor.oak', tint: 'rgba(45,46,42,.35)' },
        { id: 'attic-hall', name: '阁楼平台', purpose: 'stairs', x: 108, y: 352, width: 744, height: 200, floorAsset: 'floor.oak', tint: 'rgba(27,41,37,.31)' },
      ],
      walls: [...outerWalls(), { id: 'f3-v-a', x: 602, y: 50, width: 18, height: 144 }, { id: 'f3-v-b', x: 602, y: 270, width: 18, height: 82 }, { id: 'f3-h-a', x: 90, y: 334, width: 220, height: 18 }, { id: 'f3-h-b', x: 386, y: 334, width: 484, height: 18 }],
      doors: [door('f3-store', '储物间门', 611, 194, Math.PI / 2, 0, Math.PI / 2), door('f3-loft', '阁楼门', 310, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f3-unknown', name: '阁楼未知目标', position: { x: 720, y: 182 }, facing: 2.2, role: 'unknown', behavior: 'hiding', asset: 'character.resident' },
        { id: 'f3-hostile', name: '阁楼威胁', position: { x: 480, y: 210 }, facing: 1.2, role: 'hostile', behavior: 'patrol', asset: 'character.resident' },
      ],
      lights: [{ id: 'f3-desk', position: { x: 405, y: 180 }, radius: 190, intensity: .48, enabled: true }],
    },
  ],
};
