import type { AssetRecipe, BuildingScene, DoorSpec, InteractionProfile, RectSpec } from './types';

const interaction = (
  prompt: string,
  actions: InteractionProfile['actions'],
  states: InteractionProfile['states'],
  motion: InteractionProfile['motion'],
): InteractionProfile => ({
  prompt,
  actions,
  states,
  defaultState: states[0].id,
  motion,
  maxDistance: 92,
  facingDot: -0.05,
  durationMs: motion === 'hinge' ? 620 : motion === 'translate' ? 520 : 360,
});

const outerWalls = (entry = false): RectSpec[] => [
  { id: 'outer-n', x: 90, y: 50, width: 780, height: 18 },
  { id: 'outer-w', x: 90, y: 50, width: 18, height: 520 },
  { id: 'outer-e', x: 852, y: 50, width: 18, height: 520 },
  ...(entry
    ? [
        { id: 'outer-s-a', x: 90, y: 552, width: 86, height: 18 },
        { id: 'outer-s-b', x: 256, y: 552, width: 614, height: 18 },
      ]
    : [{ id: 'outer-s', x: 90, y: 552, width: 780, height: 18 }]),
];

const door = (
  id: string,
  name: string,
  x: number,
  y: number,
  angle: number,
  min: number,
  max: number,
): DoorSpec => ({
  id,
  name,
  hinge: { x, y },
  length: 76,
  width: 11,
  closedAngle: angle,
  minAngle: min,
  maxAngle: max,
  frontAsset: 'door.painted.front',
  backAsset: 'door.painted.back',
});

export const assetRecipes: AssetRecipe[] = [
  {
    id: 'reference.townhouse-art-direction-v1',
    name: '联排住宅美术总参考',
    kind: 'prop',
    description: '统一房屋的色温、材质分区、家具比例、磨损语言与楼梯构造；整图永不进入运行时渲染。',
    prompt: 'Original premium four-storey London townhouse cutaway at night, cool moonlight and warm practical lights, aged ivory plaster, dark walnut, muted olive and oxblood accents, readable separately constructed doors, drawers and staircase.',
    source: '/assets/reference-townhouse-art-direction-v1.png',
    usage: 'reference-study',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 12, y: 7.5 },
    pivot: { x: 0.5, y: 0.5 },
    referenceStudy: {
      source: '/assets/reference-townhouse-art-direction-v1.png',
      learn: ['proportion', 'material-zones', 'wear-language', 'color-palette'],
      runtimeRule: 'never-render-directly',
    },
    geometry: {
      source: 'procedural',
      primitiveFamily: 'streamed-townhouse-floor-kit',
      independentlyModeledParts: ['walls', 'wainscot', 'windows', 'stairs', 'railings', 'doors', 'furniture'],
    },
  },
  {
    id: 'floor.herringbone',
    name: '旧人字木地板',
    kind: 'tile',
    description: '可无缝平铺；图像只定义反照率，阴影由引擎计算。',
    prompt: 'Seamless worn oak plank floor texture, strict orthographic top-down, neutral diffuse light, no objects, no perspective, no shadows.',
    source: '/assets/floor-herringbone-v2.png',
    usage: 'runtime-texture',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 2, y: 2 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.3, friction: 0.72 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: 2, y: 2 } },
  },
  {
    id: 'floor.carpet',
    name: '磨损地毯',
    kind: 'tile',
    description: '卧室和楼梯平台使用的低反差地毯。',
    prompt: 'Seamless worn charcoal loop-pile carpet texture, strict top-down, flat diffuse light, subtle domestic wear, no objects.',
    source: '/assets/floor-carpet-v2.png',
    usage: 'runtime-texture',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 2, y: 2 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.18, friction: 0.9 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: 2, y: 2 } },
  },
  {
    id: 'floor.checker', name: '厨房棋盘砖', kind: 'tile',
    description: '厨房与浴室使用的低反光旧瓷砖。',
    prompt: 'Seamless old ivory and charcoal checker tile, strict top-down, neutral diffuse light, no objects.',
    source: '/assets/floor-checker-v2.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: 2, y: 2 }, pivot: { x: .5, y: .5 },
    material: { penetration: 'hard', occlusion: .22, friction: .68 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: 2, y: 2 } },
  },
  {
    id: 'floor.concrete', name: '地下室混凝土', kind: 'tile',
    description: '潮湿但没有烘焙灯光的地下室地面。',
    prompt: 'Seamless aged basement concrete, strict top-down, neutral diffuse light, no objects.',
    source: '/assets/floor-concrete-v2.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: 2, y: 2 }, pivot: { x: .5, y: .5 },
    material: { penetration: 'hard', occlusion: .32, friction: .74 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: 2, y: 2 } },
  },
  {
    id: 'material.wallpaper.ivory', name: '象牙旧墙纸材质', kind: 'material',
    description: 'GPT 生成的可平铺 base-color；墙体 Mesh、厚度和碰撞由引擎创建。',
    prompt: 'Seamless aged warm ivory townhouse plaster and faded wallpaper fiber, neutral diffuse surface scan.',
    source: '/assets/mat-wallpaper-ivory-v1.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: 1.5, y: 1.5 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: 1.5, y: 1.5 } },
  },
  {
    id: 'material.upholstery.olive', name: '橄榄绿旧布料', kind: 'material',
    description: '用于沙发 3D Mesh 的织物美学，不包含沙发轮廓。',
    prompt: 'Seamless worn olive woven upholstery fabric, flat surface scan, no folds or object silhouette.',
    source: '/assets/mat-upholstery-olive-v1.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .65, y: .65 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: .65, y: .65 } },
  },
  {
    id: 'material.leather.olive.base', name: '旧橄榄皮革 · Base Color', kind: 'material',
    description: '从沙发四视图的材质语言中分离出的无光照反照率，不携带物体轮廓。',
    prompt: 'Seamless aged muted olive leather base-color texture, neutral flat scan, fine grain and restrained contact wear, no lighting, no object silhouette.',
    source: '/assets/mat-leather-olive-base-v1.webp', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .72, y: .72 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: .72, y: .72 } },
  },
  {
    id: 'material.leather.olive.normal', name: '旧橄榄皮革 · Normal', kind: 'material',
    description: '皮革细粒度切线空间法线；只提供微表面，不伪造沙发褶皱。',
    prompt: 'Seamless tangent-space normal map for fine aged leather grain, flat neutral surface, no folds, no object silhouette.',
    source: '/assets/mat-leather-olive-normal-v1.webp', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .72, y: .72 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'normal', tileable: true, colorSpace: 'linear', metersPerTile: { x: .72, y: .72 } },
  },
  {
    id: 'material.leather.olive.roughness', name: '旧橄榄皮革 · Roughness', kind: 'material',
    description: '控制旧皮革漫反射与接触区轻微抛光，不包含烘焙阴影。',
    prompt: 'Seamless grayscale roughness map for aged olive leather, mostly matte with subtle polished contact wear, no lighting or silhouette.',
    source: '/assets/mat-leather-olive-roughness-v1.webp', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .72, y: .72 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'roughness', tileable: true, colorSpace: 'linear', metersPerTile: { x: .72, y: .72 } },
  },
  {
    id: 'material.walnut', name: '深色旧胡桃木', kind: 'material',
    description: '桌椅、床架和楼梯共用的可平铺木材 base-color。',
    prompt: 'Seamless old dark walnut furniture wood, fine straight grain, neutral diffuse surface scan.',
    source: '/assets/mat-walnut-v1.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .8, y: .8 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: .8, y: .8 } },
  },
  {
    id: 'material.sage-paint', name: '鼠尾草绿旧漆', kind: 'material',
    description: '柜体与独立柜门 Mesh 共用的漆面材质。',
    prompt: 'Seamless worn muted sage-green painted wood, subtle chips, no panels or hardware.',
    source: '/assets/mat-sage-paint-v1.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .75, y: .75 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: .75, y: .75 } },
  },
  {
    id: 'material.tactical-fabric', name: '战术防撕裂布', kind: 'material',
    description: '角色 3D rig 的服装材质；走路来自骨骼关节动画。',
    prompt: 'Seamless charcoal tactical ripstop fabric, matte, neutral diffuse surface scan, no logo.',
    source: '/assets/mat-tactical-fabric-v1.png', usage: 'runtime-texture', state: 'ready', side: 'top',
    physicalSize: { x: .35, y: .35 }, pivot: { x: .5, y: .5 },
    texture: { semantic: 'base-color', tileable: true, colorSpace: 'srgb', metersPerTile: { x: .35, y: .35 } },
  },
  {
    id: 'wall.paper.face',
    name: '墙纸内墙面',
    kind: 'wall-face',
    description: '熟悉的住家墙面；声音遮挡与穿透参数独立保存。',
    prompt: 'Straight-on faded domestic wallpaper wall face, subtle age and lived-in detail, seamless, neutral diffuse light, no decor.',
    usage: 'runtime-texture',
    state: 'recipe',
    side: 'front',
    physicalSize: { x: 2, y: 2.6 },
    pivot: { x: 0.5, y: 1 },
    material: { penetration: 'soft', occlusion: 0.55, friction: 0.6 },
  },
  {
    id: 'wall.plaster.top',
    name: '墙体切面',
    kind: 'wall-face',
    description: '俯视时看到的墙厚切面，与墙纸分开生成。',
    prompt: 'Orthographic top cut surface of an aged plaster and timber stud interior wall strip, isolated texture, no perspective.',
    usage: 'runtime-texture',
    state: 'recipe',
    side: 'top',
    physicalSize: { x: 2, y: 0.18 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.55, friction: 0.6 },
  },
  {
    id: 'door.painted.front',
    name: '门 · 走廊面',
    kind: 'door-face',
    description: '门的走廊一面；门轴、厚度、锁和碰撞不烘进图里。',
    prompt: 'Single aged off-white painted townhouse interior door front face, orthographic, isolated, full rectangle, brass handle, no frame.',
    usage: 'runtime-texture',
    state: 'recipe',
    side: 'front',
    physicalSize: { x: 0.86, y: 2.04 },
    pivot: { x: 0, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.7, friction: 0.55 },
  },
  {
    id: 'door.painted.back',
    name: '门 · 房间面',
    kind: 'door-face',
    description: '同一扇门的背面，必须独立生成以支持推门观察。',
    prompt: 'Matching reverse face of one aged off-white painted townhouse interior door, orthographic, isolated, brass handle opposite side, no frame.',
    usage: 'runtime-texture',
    state: 'recipe',
    side: 'back',
    physicalSize: { x: 0.86, y: 2.04 },
    pivot: { x: 0, y: 0.5 },
    material: { penetration: 'medium', occlusion: 0.7, friction: 0.55 },
  },
  {
    id: 'prop.bed',
    name: '未整理床铺',
    kind: 'prop',
    description: '家具是透明背景图，遮挡体和可藏匿区域另存。',
    prompt: 'One lived-in unmade bed, strict 90-degree overhead, grounded realism, transparent background, no baked cast shadow.',
    source: '/assets/prop-bed-v2.png',
    usage: 'reference-study',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 2, y: 1.5 },
    pivot: { x: 0.5, y: 0.5 },
    material: { penetration: 'soft', occlusion: 0.45, friction: 0.8 },
    referenceStudy: { source: '/assets/prop-bed-v2.png', learn: ['silhouette', 'proportion', 'material-zones', 'wear-language', 'color-palette'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'upholstered-bed', independentlyModeledParts: ['frame', 'mattress', 'pillows', 'under-bed-drawer'] },
    interaction: interaction('Q 翻找床下', ['search', 'hide'], [
      { id: 'closed', label: '未翻找', asset: 'prop.bed' },
      { id: 'searched', label: '床下已打开', asset: 'prop.bed.searched' },
    ], 'swap'),
  },
  {
    id: 'prop.bed.searched', name: '床铺 · 已翻找', kind: 'prop',
    description: '与床铺母版对齐的交互状态，只由床铺状态机引用。',
    prompt: 'Matching searched-state edit of the approved top-down bed, transparent, under-bed drawer open.',
    source: '/assets/prop-bed-searched-v2.png', usage: 'reference-study', state: 'ready', side: 'top',
    physicalSize: { x: 2, y: 1.5 }, pivot: { x: .5, y: .5 },
    referenceStudy: { source: '/assets/prop-bed-searched-v2.png', learn: ['silhouette', 'proportion', 'material-zones'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'upholstered-bed-state', independentlyModeledParts: ['under-bed-drawer'] },
  },
  {
    id: 'prop.sofa', name: '三座沙发', kind: 'prop',
    description: '首个 Hero 生产样板：四视图锁定造型，参数蓝图重建真实部件，三张 PBR 贴图只描述表面。',
    prompt: 'Production multi-view modeling sheet for one late-century three-seat olive leather townhouse sofa; exact front, left, back and top identity; neutral orthographic studio light.',
    source: '/assets/reference-sofa-multiview-v1.png', state: 'ready', side: 'top',
    usage: 'reference-study',
    physicalSize: { x: 2.2, y: .9 }, pivot: { x: .5, y: .5 },
    referenceStudy: {
      source: '/assets/reference-sofa-multiview-v1.png',
      views: ['front', 'left', 'back', 'top'],
      learn: ['silhouette', 'proportion', 'material-zones', 'wear-language', 'color-palette'],
      runtimeRule: 'never-render-directly',
    },
    geometry: {
      source: 'procedural',
      qualityTier: 'hero',
      primitiveFamily: 'rounded-upholstery-and-lathed-wood',
      blueprintId: 'sofa.late-century.v1',
      fallbackPrimitiveFamily: 'three-seat-sofa-graybox',
      independentlyModeledParts: [
        'walnut-frame', 'seat-deck', 'arm-supports', 'arm-rolls', 'seat-cushions',
        'back-cushions', 'piping', 'turned-legs',
      ],
    },
    pbr: {
      baseColorAsset: 'material.leather.olive.base',
      normalAsset: 'material.leather.olive.normal',
      roughnessAsset: 'material.leather.olive.roughness',
      texelDensityPxPerMeter: 512,
    },
    quality: {
      status: 'production', minBevelRadiusM: .018, triangleBudget: 32000, maxDrawCalls: 6, lods: 1,
    },
    interaction: interaction('Q 推动沙发', ['inspect', 'push'], [
      { id: 'rest', label: '原位', asset: 'prop.sofa' }, { id: 'shifted', label: '已推动', asset: 'prop.sofa' },
    ], 'translate'),
  },
  {
    id: 'prop.kitchen', name: 'L 型厨房柜体', kind: 'prop',
    description: '厨房本体与柜门状态分离；每扇门是独立交互子部件，禁止整组同时开。',
    prompt: 'Top-down L-shaped old townhouse kitchen, transparent, all cabinet fronts closed.',
    source: '/assets/prop-kitchen-v2.png', state: 'ready', side: 'top',
    usage: 'reference-study',
    physicalSize: { x: 3.1, y: 2.1 }, pivot: { x: .5, y: .5 },
    referenceStudy: { source: '/assets/prop-kitchen-v2.png', learn: ['silhouette', 'proportion', 'material-zones', 'wear-language', 'color-palette'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'l-kitchen', independentlyModeledParts: ['carcass', 'worktop', 'cabinet-left', 'drawer-sink', 'cabinet-stove', 'cabinet-side'] },
    interaction: interaction('靠近具体柜门后按 Q', ['inspect'], [{ id: 'closed', label: '柜体' }], 'none'),
  },
  {
    id: 'prop.cabinet-door.open', name: '独立柜门叶 · 打开', kind: 'prop',
    description: '供每个柜门子实例复用；铰链、角度和开关状态仍属于子部件数据。',
    prompt: 'One opened worn sage-green cabinet door leaf, isolated transparent alpha, overhead game view.',
    source: '/assets/prop-cabinet-door-open-v2.png', usage: 'reference-study', state: 'ready', side: 'top',
    physicalSize: { x: .48, y: .72 }, pivot: { x: 0, y: .5 },
    referenceStudy: { source: '/assets/prop-cabinet-door-open-v2.png', learn: ['silhouette', 'proportion', 'material-zones'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'hinged-cabinet-leaf', independentlyModeledParts: ['leaf', 'handle', 'hinge-pivot'] },
  },
  {
    id: 'prop.drawer.open', name: '独立抽屉盒 · 打开', kind: 'prop',
    description: '抽屉子实例的拉出状态，不会联动同一柜体的其他抽屉。',
    prompt: 'One open sage-green kitchen drawer box, isolated transparent alpha, overhead game view.',
    source: '/assets/prop-drawer-open-v2.png', usage: 'reference-study', state: 'ready', side: 'top',
    physicalSize: { x: .56, y: .65 }, pivot: { x: .5, y: 0 },
    referenceStudy: { source: '/assets/prop-drawer-open-v2.png', learn: ['silhouette', 'proportion', 'material-zones'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'sliding-drawer-box', independentlyModeledParts: ['box', 'front', 'handle'] },
  },
  {
    id: 'prop.table', name: '椭圆餐桌', kind: 'prop',
    description: '餐桌和椅子分开，椅子可以单独移动。',
    prompt: 'Single old oval wooden dining table, strict top-down, transparent, no chairs.',
    source: '/assets/prop-dining-table-v2.png', state: 'ready', side: 'top',
    usage: 'reference-study',
    physicalSize: { x: 1.8, y: 1.05 }, pivot: { x: .5, y: .5 },
    referenceStudy: { source: '/assets/prop-dining-table-v2.png', learn: ['silhouette', 'proportion', 'material-zones', 'wear-language'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'oval-table', independentlyModeledParts: ['top', 'legs'] },
    interaction: interaction('Q 检查餐桌', ['inspect'], [{ id: 'rest', label: '静置', asset: 'prop.table' }], 'none'),
  },
  {
    id: 'prop.chair', name: '单体餐椅', kind: 'prop',
    description: '每把椅子都是独立实例，可单独推拉，不与桌子合图。',
    prompt: 'One vintage wooden dining chair, strict top-down, transparent, no table.',
    source: '/assets/prop-dining-chair-v2.png', state: 'ready', side: 'top',
    usage: 'reference-study',
    physicalSize: { x: .55, y: .55 }, pivot: { x: .5, y: .5 },
    referenceStudy: { source: '/assets/prop-dining-chair-v2.png', learn: ['silhouette', 'proportion', 'material-zones', 'wear-language'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'dining-chair', independentlyModeledParts: ['seat', 'back', 'legs'] },
    interaction: interaction('Q 拉开椅子', ['push', 'move'], [
      { id: 'tucked', label: '收拢', asset: 'prop.chair' }, { id: 'pulled', label: '拉开', asset: 'prop.chair' },
    ], 'translate'),
  },
  {
    id: 'prop.stairs', name: '木楼梯', kind: 'prop',
    description: '楼梯图片只负责外观；楼层目标和传送锚点由 portal 数据保存。',
    prompt: 'Old townhouse staircase, strict top-down, transparent, no person.',
    source: '/assets/prop-stairs-v2.png', state: 'ready', side: 'top',
    usage: 'reference-study',
    physicalSize: { x: 1.35, y: 2.2 }, pivot: { x: .5, y: .5 },
    referenceStudy: { source: '/assets/prop-stairs-v2.png', learn: ['silhouette', 'proportion', 'material-zones', 'wear-language'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'straight-staircase', independentlyModeledParts: ['treads', 'risers', 'newel-posts', 'balusters', 'handrails'] },
    interaction: interaction('沿踏步走到楼梯尽头切换楼层', ['traverse'], [{ id: 'ready', label: '自动通行', asset: 'prop.stairs' }], 'portal'),
  },
  {
    id: 'character.operator',
    name: '战术操作员',
    kind: 'character',
    description: '玩家渲染图；移动胶囊、视野和队伍逻辑全部独立。',
    prompt: 'One fictional modern tactical response operator, strict 90-degree overhead, dark unbranded equipment, transparent background.',
    source: '/assets/operator-walk-4x4-rgba.png',
    usage: 'runtime-sprite',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 0.62, y: 0.62 },
    pivot: { x: 0.5, y: 0.6 },
    atlas: { columns: 4, rows: 4, fps: 8, directions: ['north', 'east', 'south', 'west'] },
    geometry: { source: 'procedural', primitiveFamily: 'articulated-humanoid-rig', independentlyModeledParts: ['torso', 'head', 'arms', 'legs', 'equipment'] },
    animation: { skeleton: 'gami-humanoid-v1', rootMotion: 'engine', clips: [
      { id: 'idle', loop: true, duration: 1.8, status: 'implemented' },
      { id: 'walk', loop: true, duration: .78, status: 'implemented' },
      { id: 'push-door', loop: false, duration: .62, status: 'required' },
      { id: 'search', loop: false, duration: .8, status: 'required' },
      { id: 'crouch-walk', loop: true, duration: 1.05, status: 'required' },
      { id: 'stairs-up', loop: true, duration: .9, status: 'required' },
      { id: 'stairs-down', loop: true, duration: .9, status: 'required' },
    ] },
  },
  {
    id: 'character.resident',
    name: '住户基础体',
    kind: 'character',
    description: '演示住户。实际生产中由角色母版继续编辑成不同服装和状态。',
    prompt: 'One ordinary adult townhouse resident, strict 90-degree overhead, neutral clothes, transparent background, no weapon.',
    source: '/assets/character-explorer.png',
    usage: 'reference-study',
    state: 'ready',
    side: 'top',
    physicalSize: { x: 0.58, y: 0.58 },
    pivot: { x: 0.5, y: 0.58 },
    referenceStudy: { source: '/assets/character-explorer.png', learn: ['silhouette', 'proportion', 'material-zones', 'color-palette'], runtimeRule: 'never-render-directly' },
    geometry: { source: 'procedural', primitiveFamily: 'articulated-humanoid-rig', independentlyModeledParts: ['torso', 'head', 'arms', 'legs'] },
    animation: { skeleton: 'gami-humanoid-v1', rootMotion: 'engine', clips: [
      { id: 'idle', loop: true, duration: 2.1, status: 'implemented' },
      { id: 'walk', loop: true, duration: .9, status: 'implemented' },
      { id: 'sleep', loop: true, duration: 3.4, status: 'implemented' },
      { id: 'hide-crouch', loop: true, duration: 2.6, status: 'implemented' },
      { id: 'startle', loop: false, duration: .7, status: 'required' },
      { id: 'surrender', loop: true, duration: 1.7, status: 'required' },
    ] },
  },
];

export const buildingScene: BuildingScene = {
  version: 2,
  name: 'GAMI ENGINE / NO. 47 TOWNHOUSE DEMO',
  world: { width: 960, height: 620, pixelsPerMeter: 80 },
  renderer: { mode: '3d', engine: 'three', floorStreaming: true, defaultCamera: 'editor' },
  styleLock: {
    id: 'moonlit-lived-in-townhouse-v2',
    projection: '3D cutaway building with editor orbit and player-follow camera',
    lighting: 'generated images are neutral material studies; Three.js owns all runtime light, shadow and night vision',
    palette: 'charcoal green and smoke blue shadows, aged ivory plaster, dark walnut, oxblood, muted olive, tarnished brass',
    negative: 'no franchise characters, no perspective, no complete room scene, no baked cast shadows, no text, no watermark',
  },
  assets: assetRecipes,
  floors: [
    {
      id: 'b1', index: 0, name: 'B1', subtitle: '地下室 · 设备 / 储藏', spawn: { x: 245, y: 455 },
      stairs: { id: 'stairs-b1', x: 112, y: 370, width: 108, height: 155, toUp: 'f1', autoTraverse: true, upDirection: 'north', rise: 1.04 },
      rooms: [
        { id: 'boiler', name: '锅炉间', purpose: 'utility', x: 108, y: 68, width: 270, height: 270, floorAsset: 'floor.concrete', tint: 'rgba(40,64,55,.12)' },
        { id: 'store', name: '储藏间', purpose: 'storage', x: 396, y: 68, width: 456, height: 270, floorAsset: 'floor.concrete', tint: 'rgba(48,51,46,.12)' },
        { id: 'cellar', name: '地下走廊', purpose: 'hall', x: 108, y: 356, width: 744, height: 196, floorAsset: 'floor.concrete', tint: 'rgba(20,34,30,.14)' },
      ],
      walls: [...outerWalls(), { id: 'b1-v-a', x: 378, y: 50, width: 18, height: 126 }, { id: 'b1-v-b', x: 378, y: 252, width: 18, height: 104 }, { id: 'b1-h-a', x: 90, y: 338, width: 202, height: 18 }, { id: 'b1-h-b', x: 368, y: 338, width: 502, height: 18 }],
      obstacles: [
        { id: 'b1-boiler-body', x: 144, y: 122, width: 64, height: 64 },
        { id: 'b1-box-a', x: 544, y: 105, width: 44, height: 50 },
        { id: 'b1-box-b', x: 602, y: 103, width: 44, height: 54 },
        { id: 'b1-box-c', x: 660, y: 101, width: 44, height: 58 },
      ],
      doors: [door('b1-store-door', '储藏门', 387, 176, Math.PI / 2, 0, Math.PI / 2), door('b1-hall-door', '锅炉门', 292, 347, 0, -Math.PI / 2, 0)],
      occupants: [{ id: 'b1-unknown', name: '未知住户', position: { x: 700, y: 182 }, facing: 2.4, role: 'unknown', behavior: 'hiding', asset: 'character.resident', collider: { radius: 15, blocksMovement: true } }],
      props: [{ id: 'b1-stairs-prop', name: '地下室楼梯', asset: 'prop.stairs', position: { x: 166, y: 448 }, size: { x: 96, y: 154 }, collider: { width: 96, height: 154, blocksMovement: false } }],
      lights: [{ id: 'b1-bulb', position: { x: 285, y: 208 }, radius: 180, intensity: .62, enabled: true }],
    },
    {
      id: 'f1', index: 1, name: '1F', subtitle: '入口 · 厨房 / 起居', spawn: { x: 245, y: 455 },
      stairs: { id: 'stairs-f1', x: 112, y: 352, width: 108, height: 176, toUp: 'f2', toDown: 'b1', autoTraverse: true, upDirection: 'north', rise: 1.08 },
      rooms: [
        { id: 'foyer', name: '入口厅', purpose: 'entry', x: 108, y: 68, width: 200, height: 266, floorAsset: 'floor.herringbone', tint: 'rgba(48,62,55,.07)' },
        { id: 'living', name: '起居室', purpose: 'living', x: 326, y: 68, width: 280, height: 266, floorAsset: 'floor.herringbone', tint: 'rgba(89,64,48,.06)' },
        { id: 'kitchen', name: '厨房', purpose: 'kitchen', x: 624, y: 68, width: 228, height: 266, floorAsset: 'floor.checker', tint: 'rgba(63,72,67,.08)' },
        { id: 'hall', name: '楼梯厅', purpose: 'stairs', x: 108, y: 352, width: 244, height: 200, floorAsset: 'floor.herringbone', tint: 'rgba(30,46,41,.1)' },
        { id: 'dining', name: '餐区', purpose: 'dining', x: 370, y: 352, width: 482, height: 200, floorAsset: 'floor.herringbone', tint: 'rgba(94,75,51,.05)' },
      ],
      walls: [...outerWalls(true), { id: 'f1-v1-a', x: 308, y: 50, width: 18, height: 116 }, { id: 'f1-v1-b', x: 308, y: 242, width: 18, height: 110 }, { id: 'f1-v2-a', x: 606, y: 50, width: 18, height: 172 }, { id: 'f1-v2-b', x: 606, y: 298, width: 18, height: 54 }, { id: 'f1-h-a', x: 90, y: 334, width: 236, height: 18 }, { id: 'f1-h-b', x: 402, y: 334, width: 468, height: 18 }],
      obstacles: [],
      doors: [door('f1-entry', '入口门', 176, 561, 0, -Math.PI / 2, 0), door('f1-living', '起居室门', 317, 166, Math.PI / 2, 0, Math.PI / 2), door('f1-kitchen', '厨房门', 615, 222, Math.PI / 2, 0, Math.PI / 2), door('f1-dining', '餐区门', 326, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f1-resident-a', name: '住户 A', position: { x: 552, y: 276 }, facing: 2.55, role: 'civilian', behavior: 'frozen', asset: 'character.resident', collider: { radius: 16, blocksMovement: true } },
        { id: 'f1-unknown-b', name: '未知 B', position: { x: 760, y: 270 }, facing: 1.5, role: 'unknown', behavior: 'investigate', asset: 'character.resident', collider: { radius: 16, blocksMovement: true }, navigation: { speed: 34, mode: 'ping-pong', waypoints: [{ x: 760, y: 270 }, { x: 660, y: 270 }] } },
        { id: 'f1-hostile-c', name: '威胁 C', position: { x: 810, y: 510 }, facing: -1.2, role: 'hostile', behavior: 'patrol', asset: 'character.resident', collider: { radius: 16, blocksMovement: true }, navigation: { speed: 42, mode: 'loop', waypoints: [{ x: 810, y: 510 }, { x: 810, y: 390 }, { x: 430, y: 390 }, { x: 430, y: 510 }] } },
      ],
      props: [
        { id: 'f1-sofa', name: '起居室沙发', asset: 'prop.sofa', position: { x: 466, y: 144 }, size: { x: 180, y: 86 }, collider: { width: 154, height: 58 }, interaction: assetRecipes.find((item) => item.id === 'prop.sofa')?.interaction },
        { id: 'f1-kitchen-units', name: '厨房柜体', asset: 'prop.kitchen', position: { x: 741, y: 163 }, size: { x: 205, y: 137 }, collider: { width: 194, height: 72 }, parts: [
          { id: 'cabinet-left', name: '左侧柜门', position: { x: 696, y: 180 }, interaction: interaction('Q 打开左侧柜门', ['open', 'search'], [{ id: 'closed', label: '关闭' }, { id: 'open', label: '打开', asset: 'prop.cabinet-door.open' }], 'hinge') },
          { id: 'drawer-sink', name: '水槽抽屉', position: { x: 742, y: 190 }, interaction: interaction('Q 拉开水槽抽屉', ['open', 'search'], [{ id: 'closed', label: '关闭' }, { id: 'open', label: '打开', asset: 'prop.drawer.open' }], 'translate') },
          { id: 'cabinet-stove', name: '炉灶下柜门', position: { x: 790, y: 188 }, interaction: interaction('Q 打开炉灶下柜门', ['open', 'search'], [{ id: 'closed', label: '关闭' }, { id: 'open', label: '打开', asset: 'prop.cabinet-door.open' }], 'hinge') },
          { id: 'cabinet-side', name: '侧柜门', position: { x: 666, y: 224 }, interaction: interaction('Q 打开侧柜门', ['open', 'search'], [{ id: 'closed', label: '关闭' }, { id: 'open', label: '打开', asset: 'prop.cabinet-door.open' }], 'hinge') },
        ] },
        { id: 'f1-table', name: '餐桌', asset: 'prop.table', position: { x: 620, y: 454 }, size: { x: 148, y: 88 }, collider: { width: 132, height: 72 } },
        { id: 'f1-chair-a', name: '餐椅 A', asset: 'prop.chair', position: { x: 515, y: 454 }, size: { x: 48, y: 48 }, rotation: Math.PI / 2, collider: { width: 38, height: 38 }, interaction: assetRecipes.find((item) => item.id === 'prop.chair')?.interaction },
        { id: 'f1-chair-b', name: '餐椅 B', asset: 'prop.chair', position: { x: 725, y: 454 }, size: { x: 48, y: 48 }, rotation: -Math.PI / 2, collider: { width: 38, height: 38 }, interaction: assetRecipes.find((item) => item.id === 'prop.chair')?.interaction },
        { id: 'f1-stairs-prop', name: '主楼梯', asset: 'prop.stairs', position: { x: 166, y: 440 }, size: { x: 96, y: 166 }, collider: { width: 96, height: 166, blocksMovement: false } },
      ],
      lights: [
        { id: 'f1-lamp', position: { x: 470, y: 190 }, radius: 210, intensity: .74, enabled: true },
        { id: 'f1-kitchen-light', position: { x: 744, y: 210 }, radius: 155, intensity: .42, enabled: true },
        { id: 'f1-stair-sconce', position: { x: 244, y: 408 }, radius: 125, intensity: .34, enabled: true },
        { id: 'f1-dining-pendant', position: { x: 620, y: 454 }, radius: 185, intensity: .38, enabled: true },
      ],
    },
    {
      id: 'f2', index: 2, name: '2F', subtitle: '卧室 · 浴室 / 住户', spawn: { x: 245, y: 455 },
      stairs: { id: 'stairs-f2', x: 112, y: 352, width: 108, height: 176, toUp: 'f3', toDown: 'f1', autoTraverse: true, upDirection: 'north', rise: 1.08 },
      rooms: [
        { id: 'bed-a', name: '前卧室', purpose: 'bedroom', x: 108, y: 68, width: 294, height: 266, floorAsset: 'floor.carpet', tint: 'rgba(46,58,53,.24)' },
        { id: 'bath', name: '浴室', purpose: 'bathroom', x: 420, y: 68, width: 182, height: 266, floorAsset: 'floor.checker', tint: 'rgba(52,72,72,.1)' },
        { id: 'bed-b', name: '后卧室', purpose: 'bedroom', x: 620, y: 68, width: 232, height: 266, floorAsset: 'floor.carpet', tint: 'rgba(72,52,54,.24)' },
        { id: 'landing', name: '楼梯平台', purpose: 'stairs', x: 108, y: 352, width: 248, height: 200, floorAsset: 'floor.carpet', tint: 'rgba(28,42,38,.3)' },
        { id: 'nursery', name: '儿童房', purpose: 'nursery', x: 374, y: 352, width: 478, height: 200, floorAsset: 'floor.carpet', tint: 'rgba(84,76,51,.17)' },
      ],
      walls: [...outerWalls(), { id: 'f2-v1-a', x: 402, y: 50, width: 18, height: 150 }, { id: 'f2-v1-b', x: 402, y: 276, width: 18, height: 76 }, { id: 'f2-v2-a', x: 602, y: 50, width: 18, height: 112 }, { id: 'f2-v2-b', x: 602, y: 238, width: 18, height: 114 }, { id: 'f2-h-a', x: 90, y: 334, width: 190, height: 18 }, { id: 'f2-h-b', x: 356, y: 334, width: 514, height: 18 }],
      obstacles: [
        { id: 'f2-bath-fixture', x: 455, y: 92, width: 112, height: 62 },
        { id: 'f2-nursery-crib', x: 437, y: 394, width: 84, height: 116 },
      ],
      doors: [door('f2-bed-a', '前卧室门', 411, 200, Math.PI / 2, 0, Math.PI / 2), door('f2-bed-b', '后卧室门', 611, 162, Math.PI / 2, 0, Math.PI / 2), door('f2-nursery', '儿童房门', 280, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f2-sleeper', name: '熟睡住户', position: { x: 235, y: 188 }, facing: 0, role: 'civilian', behavior: 'sleeping', asset: 'character.resident', collider: { radius: 15, blocksMovement: false } },
        { id: 'f2-hidden', name: '床后未知目标', position: { x: 735, y: 260 }, facing: 2.8, role: 'unknown', behavior: 'hiding', asset: 'character.resident', collider: { radius: 14, blocksMovement: true } },
        { id: 'f2-civilian', name: '住户 D', position: { x: 552, y: 452 }, facing: -2, role: 'civilian', behavior: 'frozen', asset: 'character.resident', collider: { radius: 16, blocksMovement: true } },
        { id: 'f2-hostile', name: '威胁 E', position: { x: 790, y: 500 }, facing: -2.4, role: 'hostile', behavior: 'investigate', asset: 'character.resident', collider: { radius: 16, blocksMovement: true }, navigation: { speed: 36, mode: 'ping-pong', waypoints: [{ x: 790, y: 500 }, { x: 790, y: 390 }, { x: 700, y: 390 }] } },
      ],
      props: [
        { id: 'f2-bed-a-prop', name: '前卧室床铺', asset: 'prop.bed', position: { x: 235, y: 170 }, size: { x: 128, y: 158 }, collider: { width: 112, height: 144 }, interaction: assetRecipes.find((item) => item.id === 'prop.bed')?.interaction },
        { id: 'f2-bed-b-prop', name: '后卧室床铺', asset: 'prop.bed', position: { x: 730, y: 170 }, size: { x: 120, y: 150 }, collider: { width: 104, height: 136 }, interaction: assetRecipes.find((item) => item.id === 'prop.bed')?.interaction },
        { id: 'f2-stairs-prop', name: '二层楼梯', asset: 'prop.stairs', position: { x: 166, y: 440 }, size: { x: 96, y: 166 }, collider: { width: 96, height: 166, blocksMovement: false } },
      ],
      lights: [
        { id: 'f2-hall', position: { x: 320, y: 380 }, radius: 170, intensity: .5, enabled: true },
        { id: 'f2-bed', position: { x: 710, y: 175 }, radius: 150, intensity: .29, enabled: true },
        { id: 'f2-nursery-nightlight', position: { x: 670, y: 455 }, radius: 175, intensity: .25, enabled: true },
      ],
    },
    {
      id: 'f3', index: 3, name: '3F', subtitle: '阁楼 · 工作室 / 储物', spawn: { x: 245, y: 455 },
      stairs: { id: 'stairs-f3', x: 112, y: 352, width: 108, height: 176, toDown: 'f2', autoTraverse: true, upDirection: 'north', rise: 1.08 },
      rooms: [
        { id: 'loft', name: '阁楼工作室', purpose: 'studio', x: 108, y: 68, width: 494, height: 266, floorAsset: 'floor.herringbone', tint: 'rgba(45,58,51,.08)' },
        { id: 'attic-store', name: '封闭储物间', purpose: 'storage', x: 620, y: 68, width: 232, height: 266, floorAsset: 'floor.herringbone', tint: 'rgba(45,46,42,.13)' },
        { id: 'attic-hall', name: '阁楼平台', purpose: 'stairs', x: 108, y: 352, width: 744, height: 200, floorAsset: 'floor.herringbone', tint: 'rgba(27,41,37,.1)' },
      ],
      walls: [...outerWalls(), { id: 'f3-v-a', x: 602, y: 50, width: 18, height: 144 }, { id: 'f3-v-b', x: 602, y: 270, width: 18, height: 82 }, { id: 'f3-h-a', x: 90, y: 334, width: 220, height: 18 }, { id: 'f3-h-b', x: 386, y: 334, width: 484, height: 18 }],
      obstacles: [
        { id: 'f3-box-a', x: 656, y: 104, width: 44, height: 52 },
        { id: 'f3-box-b', x: 714, y: 102, width: 44, height: 56 },
        { id: 'f3-box-c', x: 772, y: 100, width: 44, height: 60 },
      ],
      doors: [door('f3-store', '储物间门', 611, 194, Math.PI / 2, 0, Math.PI / 2), door('f3-loft', '阁楼门', 310, 343, 0, -Math.PI / 2, 0)],
      occupants: [
        { id: 'f3-unknown', name: '阁楼未知目标', position: { x: 720, y: 182 }, facing: 2.2, role: 'unknown', behavior: 'hiding', asset: 'character.resident', collider: { radius: 14, blocksMovement: true } },
        { id: 'f3-hostile', name: '阁楼威胁', position: { x: 520, y: 280 }, facing: 1.2, role: 'hostile', behavior: 'patrol', asset: 'character.resident', collider: { radius: 16, blocksMovement: true }, navigation: { speed: 40, mode: 'loop', waypoints: [{ x: 520, y: 280 }, { x: 560, y: 110 }, { x: 300, y: 110 }, { x: 300, y: 280 }] } },
      ],
      props: [
        { id: 'f3-table', name: '工作桌', asset: 'prop.table', position: { x: 420, y: 190 }, size: { x: 150, y: 90 }, rotation: -.15, collider: { width: 134, height: 74 } },
        { id: 'f3-chair', name: '工作椅', asset: 'prop.chair', position: { x: 420, y: 270 }, size: { x: 50, y: 50 }, collider: { width: 40, height: 40 }, interaction: assetRecipes.find((item) => item.id === 'prop.chair')?.interaction },
        { id: 'f3-stairs-prop', name: '阁楼楼梯', asset: 'prop.stairs', position: { x: 166, y: 440 }, size: { x: 96, y: 166 }, collider: { width: 96, height: 166, blocksMovement: false } },
      ],
      lights: [
        { id: 'f3-desk', position: { x: 405, y: 180 }, radius: 190, intensity: .48, enabled: true },
        { id: 'f3-landing', position: { x: 245, y: 430 }, radius: 155, intensity: .3, enabled: true },
      ],
    },
  ],
};
